# Generated by Django 5.0.7 on 2024-07-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ytapp', '0002_rename_user_alluploads_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alluploads',
            old_name='username',
            new_name='usernamefk',
        ),
        migrations.RenameField(
            model_name='lastupload',
            old_name='username',
            new_name='usernamefk',
        ),
    ]
