# Generated by Django 5.0.7 on 2024-07-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ytapp', '0003_rename_username_alluploads_usernamefk_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastUpload',
        ),
    ]
